### ISSUE TITLE
Add option to use normal time instead of delta time

### ISSUE THREAD

**Issue by Xeon3D** [benedikts-workshop/ParksideView#11]
Hi.

Would it be possible to add an option for logging to use normal time instead of delta time?

Example:

2022/04/28 22:52:30

**Comment by bmuessig** [comment]
Hi, sure this should be easy to add. I'll take care of it tomorrow.

**Comment by Xeon3D** [comment]
Great! I'll be waiting!

I've also made an unofficial Portuguese translation, will have to update my "fork" and send you a PR

**Comment by bmuessig** [comment]
I've made the changes but I can't test it, as I don't have the hardware with me right now.
Here's a build that you can try (the changes are in the datetime branch, if you want to build it yourself):
https://github.com/benedikts-workshop/ParksideView/releases/tag/v1.7-alpha

I am happy to include your Portuguese translation, if you make a PR.

**Comment by Xeon3D** [comment]
I've just tested it and it works great. 

Also, I'm testing with a PDM-300-C3 (and not C2) which is currently on sale on ALDI in my country. It's also compatible (Same PCB).

**Comment by bmuessig** [comment]
@Xeon3D Hello Mr. Alves, I just wanted to know if you saw my follow-up on https://github.com/benedikts-workshop/ParksideView/issues/14?
