### ISSUE TITLE
GUI tweaks

### ISSUE THREAD

**Issue by bmuessig** [benedikts-workshop/ParksideView#14]
@Xeon3D I've made some more GUI tweaks to prevent overflow for the other languages.
A build for all three languages is available here: https://github.com/benedikts-workshop/ParksideView/releases/tag/v1.7-beta

It would be great, if you could give it a test. If it works, I'll release it properly.

Thanks,
Benedikt

**Comment by Xeon3D** [comment]
Hello.

I've tested it and it works fine.

**Comment by bmuessig** [comment]
Thanks for testing
